AWSTemplateFormatVersion: 2010-09-09
Description: |
  This CloudFormation Template was written for runnig Kittens Carousel Static Website on
  is dowloaded form my Public Github repository, then deployed on Apache Web Server

Resources:
 WebServerSecurityGroup:
   Type: AWS::EC2::SecurityGroup
   Properties:
     GroupDescription: Enable HTTP for Apache Web Server and SSH for secure connection
     SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80  
        ToPort: 80
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 22 
        ToPort: 22
        CidrIp: 0.0.0.0/0
  WebServerHost:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0022f774911c1d690
      InstanceType: t2.micro
      KeyName: formast
      SecurityGroupIds:
        !Ref WebServerSecurityGroup
      Tags:
        - Key: Name
          Value: Web Server of ${AWS::StackName} Stack
      UserData:
        Fn::Base64:
          !Sub |
            # /bin/bash
            yum update -y
            yum install httpd -y
            cd /var/www/html
      Volumes:
        Volumes
  
Outputs: